#docker compose down && docker compose build --no-cache && docker compose up --force-recreate -d
version: '3'
services:    
  eureka-server-peer-1:
    build: Service-registry
    image: my-eureka-builder-image
    container_name: eureka-server-peer-1
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=peer-1
      - PEER_2_URL=http://172.20.0.3:9002/eureka/
      - PEER_3_URL=http://172.20.0.4:9003/eureka/
      - LOGSTASH_DESTINATION_ONE=172.20.0.13:5000
      - LOGSTASH_DESTINATION_TWO=172.20.0.13:5000
      - LOGSTASH_DESTINATION_THREE=172.20.0.14:5000
    networks:
      masterNetwork:
        ipv4_address: 172.20.0.2

  eureka-server-peer-2:
    build: Service-registry
    image: my-eureka-builder-image
    container_name: eureka-server-peer-2
    ports:
      - "9002:9002"
    environment:
      - SPRING_PROFILES_ACTIVE=peer-2
      - PEER_1_URL=http://172.20.0.2:9001/eureka/
      - PEER_3_URL=http://172.20.0.4:9003/eureka/
      - LOGSTASH_DESTINATION_ONE=172.20.0.13:5000
      - LOGSTASH_DESTINATION_TWO=172.20.0.13:5000
      - LOGSTASH_DESTINATION_THREE=172.20.0.14:5000
    networks:
      masterNetwork:
        ipv4_address: 172.20.0.3

  eureka-server-peer-3:
    build: Service-registry
    image: my-eureka-builder-image
    container_name: eureka-server-peer-3
    ports:
      - "9003:9003"
    environment:
      - SPRING_PROFILES_ACTIVE=peer-3
      - PEER_1_URL=http://172.20.0.2:9001/eureka/
      - PEER_2_URL=http://172.20.0.3:9002/eureka/
      - LOGSTASH_DESTINATION_ONE=172.20.0.13:5000
      - LOGSTASH_DESTINATION_TWO=172.20.0.13:5000
      - LOGSTASH_DESTINATION_THREE=172.20.0.14:5000
    networks:
      masterNetwork:
        ipv4_address: 172.20.0.4

networks:
  masterNetwork:
    name: masterNetwork
    external: true